name: "Markdown to Gempost"

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'markdown/incoming/**'

concurrency:
  group: md2gmi
  cancel-in-progress: true

defaults:
  run:
    shell: bash

jobs:
  md2gmi:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.MY_GH_TOKEN }}
      - uses: ./.github/actions/markdown2gempost
        with:
          input-dir: 'markdown/incoming'
          output-dir: 'gemlog'
          processed-dir: 'markdown'
      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: 'convert Markdown post to Gempost'


